### ISSUE TITLE
Incorrect indent sizes

### ISSUE THREAD

**Issue by kowalskiPl** [Ziemniakoss/sfdx-metadata-splitter#6]
Hey, I noticed that regardless of indent setting the size is always different. By different I mean one space bigger than it should be. For example setting indent size to 4 will result in indent size of 5, setting it to 3 will give 4 etc. 

This is a bit annoying but manageable. I hope for a quick fix though.

**Comment by Ziemniakoss** [comment]
Thanks again @kowalskiPl , issue was fixed in 2.0.2
